spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/authentication_service
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        delivery-timeout.ms: 120000
        retries: 100
        enable.idempotence: true
        acks: all
        spring.json.type.mapping: |
          accountCreationEvent:com.example.authenticationservice.Kafka.DTOs.AccountCreationEvent,
          otpVerification:com.example.authenticationservice.Kafka.DTOs.OtpVerification,
          passwordChangeEvent:com.example.authenticationservice.Kafka.DTOs.PasswordChangeEvent,
          userLoginEvent:com.example.authenticationservice.Kafka.DTOs.UserLoginEvent
        spring.json.add-type-info: false
    properties:
      spring:
        jackson:
          serialization:
            WRITE_DATES_AS_TIMESTAMPS: false




server:
  port: 8090