spring:
  application:
    name: exchange
  datasource:
    url: jdbc:postgresql://localhost:5435/exchange_service
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8060