spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/auth/**, /api/v1/accounts/**
        - id: wallet-service
          uri: lb://WALLET-SERVICE
          predicates:
            - Path=/api/v1/wallets/**, /api/v1/transactions/**
        - id: exchange-service
          uri: lb://EXCHANGE-SERVICE
          predicates:
            - Path=/api/v1/crypto-rates/**
server:
  port: 8222
