spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5434/wallet_service
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092, localhost:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: transactionConfirmation:com.example.wallet.Kafka.DTOs.TransactionConfirmation
    properties:
      spring:
        jackson:
          serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093
      group-id: walletGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: |
          accountCreationEvent:com.example.wallet.Kafka.DTOs.AccountCreationEvent,
          exchangeConfirmation:com.example.wallet.Kafka.DTOs.ExchangeConfirmation
      auto-offset-reset: earliest


server:
  port: 8070

application:
  config:
    authentication-url: http://localhost:8222/api/v1/accounts
