
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/wallet_service
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8070

application:
  config:
    authentication-url:http://localhost:8222/api/v1/account