
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/wallet_service
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: authGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: authenticationConfirmation:com.example.wallet.Kafka.DTOs.AccountCreationConfirmation
      auto-offset-reset: earliest

server:
  port: 8070

application:
  config:
    authentication-url: http://localhost:8090/api/v1/account
