  version: '3.8'

  services:
    mongo:
      image: mongo:latest
      container_name: mongo
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: user
        MONGO_INITDB_ROOT_PASSWORD: pass
        MONGO_INITDB_DATABASE: notification
      volumes:
        - notification-mongo-data:/data/db
    mail-dev:
      container_name: ms-mail-dev
      image: maildev/maildev
      ports:
        - 1080:1080
        - 1025:1025



  volumes:
    notification-mongo-data:

  networks:
    notification-network:
