version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_auth
    ports:
      - 5433:5432
    volumes:
      - postgres_authentication_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=authentication_service
    networks:
      - postgres_network


volumes:
  postgres_authentication_data:

networks:
  postgres_network: