version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5434:5432
    volumes:
      - wallet-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=wallet_service
    networks:
      - wallet-net
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - wallet-redis-data:/data
    ports:
      - 6379:6379
    networks:
      - wallet-net
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    ports:
      - 5540:5540
    volumes:
      - wallet-redis-insight-data:/db
    networks:
      - wallet-net


volumes:
  wallet-postgres-data:
  wallet-redis-data:
  wallet-redis-insight-data:

networks:
  wallet-net:
