version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5434:5432
    volumes:
      - wallet-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=wallet_service
    networks:
      - wallet-net


volumes:
  wallet-postgres-data:

networks:
  wallet-net:
