version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5434:5432
    volumes:
      - postgres_wallet_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=wallet_service
    networks:
      - postgres_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8084:80
    depends_on:
      - postgres
    networks:
      - postgres_network

volumes:
  postgres_wallet_data:

networks:
  postgres_network:
