
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: authentication-service


jwt:
  secret: 2$2a$12$uHQpJLE9OUEEqeKQg48CYOLC
  lifetime:
    access: 15m
    refresh: 7d
otp:
  lifetime: 5m
