version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=authentication_service
volumes:
  postgres_data: {}

networks:
  default:
    name: postgres_network
