version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_exchange
    ports:
      - 5435:5432
    volumes:
      - exchange-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=exchange_service
    networks:
      - exchange-net
  redis:
    image: redis:latest
    container_name: redis_exchange
    volumes:
      - exchange-redis-data:/data
    ports:
      - 6380:6379
    networks:
      - exchange-net


volumes:
  exchange-postgres-data:
  exchange-redis-data:

networks:
  exchange-net:
