version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5435:5432
    volumes:
      - exchange-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=exchange_service
    networks:
      - exchange-net


volumes:
  exchange-postgres-data:

networks:
  exchange-net:
